#### DO NOT CHANGE ####
site_name: Data Developer Platform
copyright: Copyright ⓒ 2023 The Modern Data Company
theme:
    name: material
    custom_dir: overrides
    language: en
    features:
        - navigation.tabs
        - navigation.sections
        - navigation.expand
        - navigation.footer
        - navigation.indexes
        - navigation.instant
        - navigation.top
        - navigation.tracking
        - toc.integrate 
    logo: assets/ddp.png
    favicon: assets/favicon.png
    logo_link_footer: https://themoderndatacompany.com
    logo_footer: /assets/ModernLogo.png
    font:
        text: Spectral
        code: Source Code Pro
    palette:
      - scheme: default
        primary: blue-grey
        accent: blue-grey
        toggle:
            icon: material/brightness-7
            name: Switch to dark mode
      - scheme: slate
        primary: grey
        accent: grey
        toggle:
            icon: material/brightness-4
            name: Switch to light mode
plugins:
    - mermaid2
    - search
extra:
  generator: true
  annotate:
    json: [.s2]
  social:
    - icon: /assets/facebook.png
      link: https://www.facebook.com/themoderndatacompany
    - icon: /assets/twitter.png
      link: https://twitter.com/TheModernDataCo
    - icon: /assets/linkedin.png
      link: https://www.linkedin.com/company/themoderndatacompany
extra_css:
    - stylesheets/extra.css
extra_javascript:
    - https://unpkg.com/mermaid@8.6.4/dist/mermaid.min.js
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.highlight
  - pymdownx.smartsymbols
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.tilde
#   - pymdownx.extra
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
      toc_depth: 5
      separator: "-"
  - attr_list
  - md_in_html

#### Update for navigation tabs/options ####      
nav:
    - Home: index.md
    - Why: why_ddp_for_data.md
    - What: what_is_data_developer_platform.md
    - Architecture: architecture.md
    - Capabilites: ddp_capabilities.md   